spring:
  application:
    name: yunshang-service-oa
  profiles:
    active: dev
  #dev开发分支 修改01 修改02 修改03 修改04 ai修改 ai修改错误 暂存之后我去修改BUG
  #我正在改东西，改到一半
  #这是master分支的提交01

  #这是master分支的提交02

  #这是master分支的提交03